version: '2'
services:
  # storybook:
  #   networks:
  #     - amazeeio-network
  #     - default
  #   environment:
  #     LAGOON_ENVIRONMENT_TYPE: 'local'
  app:
    networks:
      - amazeeio-network
      - default
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'local'
      BASIC_AUTH: 0
networks:
  amazeeio-network:
    external: true
