name: UI Libraries
on:
  push:
    paths:
      - 'packages/ripple-storybook/**'
      - 'packages/ripple-ui-core/**'
      - 'packages/ripple-ui-forms/**'
      - 'pnpm-lock.yaml'
jobs:
  Storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Storybook
        run: pnpm build:storybook
      - name: Run Storybook tests
        run: pnpm test:storybook-ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/ripple-storybook
          storybookBuildDir: 'storybook-static'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: 'gh-readonly-queue/**'
          exitOnceUploaded: true
  Component-Core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          version: 8.6.2
          run_install: true
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/ripple-ui-core
          install: false
          component: true
  Component-Forms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          version: 8.6.2
          run_install: true
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/ripple-ui-forms
          install: false
          component: true
