name: Publish Canary
on:
  push:
    branches:
      - develop
      - release/alpha-**
jobs:
  Canary:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com/'
          node-version: 20
          cache: 'pnpm'
          scope: '@dpc-sdp'
      - name: Install Dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install --frozen-lockfile
      - name: Publish canary build to @next tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "sdp.devs@dpc.vic.gov.au"
          git config --global user.name "SDP Deploy"
          pnpm config set access public
          pnpm release:publish-next --yes
