name: Publish Canary
on:
  push:
    branches:
      - develop
      - release/alpha-**
jobs:
  Canary:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com/'
          node-version: 18
          cache: 'pnpm'
          scope: '@dpc-sdp'
      - name: Install Dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install --frozen-lockfile
      - name: Publish canary build to @next tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "sdp.devs@dpc.vic.gov.au"
          git config --global user.name "SDP Deploy"
          pnpm config set access public
          pnpm release:publish-next --yes

  Update_Reference:
    runs-on: ubuntu-latest
    needs: Canary
    steps:
      - name: Kick off new pipeline to update reference site
        run: |
          curl --location --request POST 'https://circleci.com/api/v2/project/github/dpc-sdp/reference-sdp-vic-gov-au/pipeline' \
          --header 'Content-Type: application/json' \
          --header "Circle-Token: ${{ secrets.CIRCLECI_API_TOKEN }}" \
          --data '{"branch": "v2","parameters": {"update": true}}'
